### PR TITLE
Dapper seems to be an unused dependency.

### PR DESCRIPTION
**Pull request by KrisJohnstone**

### CODE REVIEW

**Comment by KrisJohnstone** [comment]
I’ll take a look when I get home from the pub.

**Comment by KrisJohnstone** [comment]
Issue appears to be appveyor not restoring a package. 
<PackageReference Include="System.Collections.Immutable" Version="1.5.0" />

**Comment by NickCraver** [comment]
Apologies I did't see this - fixed locally as part of prepping a stable (still < v1) release today. I'll see if we can merge the commit in though :)

**Comment by KrisJohnstone** [comment]
Ah then perhaps I shouldn't have raised the Issue and added the extra extension method in the new PR >.<

**Pull request merged**
