### PR TITLE
Tweak for #16: Test removing specific SDKs

### PR DESCRIPTION
**Pull request by NickCraver**
Trying tweaks to #16!

### CODE REVIEW

**Comment by NickCraver** [comment]
@deanward81 here are some tweaks to the Actions PR to remove being super specific about SDKs (also removes the fetch depth since version.json needs - but maybe I misunderstood intent there...given how small this repo is, just keeping it simple).

**Comment by deanward81** [comment]
@NickCraver last I checked `fetch-depth: 0` is needed by the checkout v2 action otherwise it does a shallow clone and nerdbank shouts angrily :/

**Comment by NickCraver** [comment]
Whaaaat? It doesn't *default* fetch full depth?

**Comment by deanward81** [comment]
Yearp, single commit by default: https://github.com/actions/checkout#whats-new

**Comment by NickCraver** [comment]
Well that's stupid - pushed a revert on that!

**Review by deanward81 — APPROVED** [review]
:+1:

**Comment by NickCraver** [comment]
Merged, just into your branch - let's see what build bits do!

**Pull request merged**
