### PR TITLE
Invalid SendForm tests

### PR DESCRIPTION
**Pull request by m0sa**
Not sure what to do about those, seems like we should get invalid SendForm Exceptions back via result.Exceptions?

### CODE REVIEW

**Comment by NickCraver** [comment]
@m0sa what's the ask? Confused by failing build atm

**Comment by m0sa** [comment]
Couple of options here, not sure what the best thing to do would be:
- don't throw immediately and handle the exception the same way as other exceptions (by passing it out via result.Error), or
- throw a better exception, that actually says which key had a null value, or
- pretend it's not an issue and convert null values into empty strings

**Comment by NickCraver** [comment]
My vote would be #1 or #3, but 3 isn't intuitive hmmmm - @deanward81 @gdalgas thoughts here?

**Comment by NickCraver** [comment]
I'd say if we're passing nulls, that's saying it's empty and I'm okay with number 3 I think

**Comment by deanward81** [comment]
+1 to number 3!

**Review by NickCraver — APPROVED** [review]
:+1:

**Pull request merged**
