### PR TITLE
Updated Dependencies, Added Patch as a Method, Ability to add Custom Headers, Fix Adding Headers Bug

### PR DESCRIPTION
**Pull request by KrisJohnstone**
Feel free to add or leave. Work has a few custom interpretation of how headers should be formatted that don't match the known headers, so needed to be able to add the header without validating.

### CODE REVIEW

**Comment by KrisJohnstone** [comment]
Sorry just saw your comment about trying to get a stable build out and here I am shifting the goal posts :/

**Comment by KrisJohnstone** [comment]
Putsreq have cleared out the code that took the headers and placed them in the body of the message. Which is why the new checkins failed, but the old ones passed.

Going to need to find an alternate method.

**Comment by KrisJohnstone** [comment]
As per usual, while I know you have another branch that you're using, feel free to merge any (or none) of the changes I've made into your build.

**Review by NickCraver — APPROVED** [review]
I missed this while it was a WIP, tidied up and merging in - thank you for adding this!

**Pull request merged**
